### PR TITLE
Add support for FiniteDuration

### PR DESCRIPTION
**Pull request by joan38**

### CODE REVIEW

**Review by michael72 — APPROVED** [review]
OK - this looks good!
I would have loved to see the Enum encoder/decoder as well :-)
@vincenzobaz -> merge it? :-)

**Comment by joan38** [comment]
See #52 for enums

**Review by vincenzobaz — APPROVED** [review]
Thank you for contributing! I like how we reached a point where adding support for new type is this straightforward.

**Comment by vincenzobaz** [comment]
Could you solve the conflicts?

**Comment by joan38** [comment]
Rebased

**Pull request merged**
