### PR TITLE
Make encoder for product match the one in Spark

### LINKED ISSUE #46: left `joinWith` not working unless all fields of the right case class are `Option`
Are you guys able to make `joinWith` work in Scala 3?
I get the following error:
```
23/10/04 18:39:59 WARN TaskSetManager: Lost task 2.0 in stage 10.0 (TID 28203) (ip-100-74-17-116.ec2.internal executor 96): java.lang.NullPointerException
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificSafeProjection.NewInstance_1$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificSafeProjection.apply(Unknown Source)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:584)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage10.hashAgg_doAggregateWithKeys_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage10.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
	at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
	at org.apache.spark.shuffle.sort.UnsafeShuffleWriter.write(UnsafeShuffleWriter.java:179)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:555)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1531)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:558)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

It sounds like the NPE is coming on executors.

Thanks

### PR DESCRIPTION
**Pull request by joan38**
Copied from https://github.com/apache/spark/blob/v3.3.1/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/ScalaReflection.scala#L389-L395

Fixes #46

### CODE REVIEW

**Comment by michael72** [comment]
Hey @joan38 ‐ the changes look good. It is around the same code lines where I did some changes in my PR. But I think those changes should be independent. Could you also check against spark v3.5.0 if that code is still the same? Also a small unit test that only works together with your changes would be great I think.
Cheers!

**Comment by joan38** [comment]
@michael72 Spark 3.5.0 completely changed how encoders work and introduced new `Expression`s. If we do what they do, this lib will not work with older Spark 3 versions.

I added more stuff that was breaking `joinWith` and a test.

**Comment by michael72** [comment]
@joan38 I currently don't have a laptop with me so it's difficult to check, but I thought between 3
4.1 and 3.5.0 they moved some code around, but in essence it was the same, but I could be completely wrong.
However taking an older version like 3.3.x as a reference is fine, but completely ignoring the newest feels wrong to me also because this library tries to remedy the very fact that evolvement of Scala was completely ignored in spark!
From my POV the PR is fine though

**Comment by vincenzobaz** [comment]
I checked out this PR and rebased on my spark version matrix PR.
`compile` and `test` are successful but `runMain`  on StarWars fails.

**Comment by michael72** [comment]
@vincenzobaz the Starwars example wouldn't work with my PR either because of the type checks applied. That example would have to be reworked. Did you copy that from somewhere or was it "handcrafted"? 😉

**Comment by vincenzobaz** [comment]
halfway copied halfway hand crafted :laughing: 
We can change it as much as we want, I do not have strong feelings about it.

In fact it is quite ugly

**Comment by joan38** [comment]
The newly added thing is this whole `AgnosticEncoder`: https://github.com/apache/spark/blob/master/sql/api/src/main/scala/org/apache/spark/sql/catalyst/encoders/AgnosticEncoder.scala#L114

If I'm not mistaken, I don't see how we can adopt it without requiring Spark 3.5.

**Comment by michael72** [comment]
Well if necessary we can copy it - or just everything that we need - same as I did (more or less) with the Helper file. Lot of this project copies parts of the spark project that fit with the encoder/decoder logic.

**Comment by joan38** [comment]
Ok, feel free to copy this PR and modify as need to move forward.
On our side we copied the library in our codebase since `joinWith`s are broken in the current state of this library.

**Comment by joan38** [comment]
Hi, did we come to a decision on this? Should we move forward with this version in order to unlock joins?

**Comment by joan38** [comment]
Superseded by #45

**Pull request closed without merging**
