### PR TITLE
Encoders

### PR DESCRIPTION
**Pull request by adpi2**
- Bump to sbt 1.5.0-RC1
- Split encoders and examples in 2 projects
- Setup munit and add `EncoderDerivationSpec`
- Use absolute path for input files
- Add failing test because of
```
java.lang.RuntimeException: Only expression encoders are supported today
```

### CODE REVIEW

**Review by vincenzobaz — APPROVED** [review]

**Comment by vincenzobaz** [comment]
Thank you for the test infrastructure!

**Comment by adpi2** [comment]
@vincenzobaz would you like to merge this branch?

**Comment by vincenzobaz** [comment]
Yes, I think we can merge it: it shows what works and what does not and we can continue an incremental workflow

**Comment by adpi2** [comment]
Ok but I cannot merge it myself

**Pull request merged**
